
#General Config Section. See https://srpc.fdd-docs.com/introduction/
[general]
	#The Application ID of the Discord App to use
	applicationID = "1362269083793363056"
	#Enable/Disable the mod
	enabled = true
	#Enable/Disable debugging mode. WARNING: MAY CAUSE LOG SPAM!
	debugging = false
	#Display the Icon and Pack Name in place of LargeImage from compatible launchers. DOES NOT WORK WITH CUSTOM APPS! ONLY THE DEFAULT ONE!
	launcherIntegration = false
	#Allow using local image files, as RPC icons
	rpcImageServer = false
	#The URL of the RPC image server that will be used for local images. Restart required when changed
	rpcImageServerUrl = "https://rpcavatar.firstdark.dev"
	#Internal Version Number. NO TOUCHY!
	version = 26

#The Game Loading event
[init]
	#Enable/Disable the Game Loading Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[init.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "Launching Game..."
		#The second line of text under the app name
		state = ""
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["commc_logo"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "v{{custom.version}} ({{game.mods}} mods)"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["{{images.player}}"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{player.name}}"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"

		#List of buttons (max 2) to show on the RPC
		[[init.presence.buttons]]
			label = "comMC Project"
			url = "https://github.com/argo20k/comMC?tab=readme-ov-file#readme-top"

#The Main Menu event
[main_menu]
	#Enable/Disable the Main Menu Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[main_menu.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "Browsing Main Menu"
		#The second line of text under the app name
		state = ""
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["commc_logo"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "v{{custom.version}} ({{game.mods}} mods)"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["{{images.player}}"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{player.name}}"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"

		#List of buttons (max 2) to show on the RPC
		[[main_menu.presence.buttons]]
			label = "comMC Project"
			url = "https://github.com/argo20k/comMC?tab=readme-ov-file#readme-top"

#The Server List event
[server_list]
	#Enable/Disable the Server List Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[server_list.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "Browsing Server List"
		#The second line of text under the app name
		state = ""
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["commc_logo"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "v{{custom.version}} ({{game.mods}} mods)"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["{{images.player}}"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{player.name}}"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"

		#List of buttons (max 2) to show on the RPC
		[[server_list.presence.buttons]]
			label = "comMC Project"
			url = "https://github.com/argo20k/comMC?tab=readme-ov-file#readme-top"

#The Realms Screen event
[realms_list]
	#Enable/Disable the Realms Screen Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[realms_list.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "Browsing Realms"
		#The second line of text under the app name
		state = ""
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["commc_logo"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "v{{custom.version}} ({{game.mods}} mods)"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["{{images.player}}"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{player.name}}"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"

		#List of buttons (max 2) to show on the RPC
		[[realms_list.presence.buttons]]
			label = "comMC Project"
			url = "https://github.com/argo20k/comMC?tab=readme-ov-file#readme-top"

#The Join Game Event
[join_game]
	#Enable/Disable the Join Game Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[join_game.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "Joining world..."
		#The second line of text under the app name
		state = ""
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["commc_logo"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "v{{custom.version}} ({{game.mods}} mods)"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["{{images.player}}"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{player.name}}"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"

		#List of buttons (max 2) to show on the RPC
		[[join_game.presence.buttons]]
			label = "comMC Project"
			url = "https://github.com/argo20k/comMC?tab=readme-ov-file#readme-top"

#The Single Player Event
[single_player]
	#Enable/Disable the Single Player Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[single_player.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "Singeplayer in \"{{world.savename}}\""
		#The second line of text under the app name
		state = ""
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["commc_logo"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "v{{custom.version}} ({{game.mods}} mods)"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["{{images.player}}"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{player.name}}"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"

		#List of buttons (max 2) to show on the RPC
		[[single_player.presence.buttons]]
			label = "comMC Project"
			url = "https://github.com/argo20k/comMC?tab=readme-ov-file#readme-top"

#The Multi Player Event
[multi_player]
	#Enable/Disable the Multi Player Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[multi_player.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "on \"{{server.name}}\" with {{server.players.count}} players"
		#The second line of text under the app name
		state = ""
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["commc_logo"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "v{{custom.version}} ({{game.mods}} mods)"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["{{images.player}}"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{player.name}}"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"

		#List of buttons (max 2) to show on the RPC
		[[multi_player.presence.buttons]]
			label = "comMC Project"
			url = "https://github.com/argo20k/comMC?tab=readme-ov-file#readme-top"

#The Realms Game Event
[realms]
	#Enable/Disable the Realms Game Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[realms.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "Playing on \"{{realm.name}}\""
		#The second line of text under the app name
		state = ""
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["commc_logo"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "v{{custom.version}} ({{game.mods}} mods)"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["{{images.player}}"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{player.name}}"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"

		#List of buttons (max 2) to show on the RPC
		[[realms.presence.buttons]]
			label = "comMC Project"
			url = "https://github.com/argo20k/comMC?tab=readme-ov-file#readme-top"

#The Paused Event
[paused]
	#Enable/Disable the Pause Event
	enabled = false

	#List of RPCs that will be displayed at random
	[[paused.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "Game Paused"
		#The second line of text under the app name
		state = ""
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["commc_logo"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "v{{custom.version}} ({{game.mods}} mods)"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["{{images.player}}"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{player.name}}"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"

		#List of buttons (max 2) to show on the RPC
		[[paused.presence.buttons]]
			label = "comMC Project"
			url = "https://github.com/argo20k/comMC?tab=readme-ov-file#readme-top"

#Fallback event for disabled events
[generic]

	#List of RPCs that will be displayed at random
	[[generic.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = ""
		#The second line of text under the app name
		state = ""
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["commc_logo"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "v{{custom.version}} ({{game.mods}} mods)"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["{{images.player}}"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{player.name}}"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"

		#List of buttons (max 2) to show on the RPC
		[[generic.presence.buttons]]
			label = "comMC Project"
			url = "https://github.com/argo20k/comMC?tab=readme-ov-file#readme-top"

#Custom Config Variables that you can use
[custom]
	#Must these variables be parsed along with other variables
	enabled = true

	#Your custom variables to add
	[[custom.variables]]
		#The name of your variable. Will be parsed into {{custom.variablename}}
		name = "version"
		#The value that this variable will output
		value = "1.8.0"

#Dimension Information Overrides
[dimension_overrides]
	#Allows you to override the displayed values for dimensions
	enabled = false

	#The Dimensions to override
	[[dimension_overrides.dimensions]]
		#The name of the Dimension/Biome to override. FORMAT: modid:dimension or modid:biome
		name = "overworld"

		#List of RPCs that will be displayed at random
		[[dimension_overrides.dimensions.presence]]
			#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
			type = "PLAYING"
			#The first line of text under the app name
			description = "{{player.name}} is in The Overworld"
			#The second line of text under the app name
			state = ""
			#The Asset ID or URLs of images to randomly use for the large image
			largeImageKey = ["overworld"]
			#The text to show when someone hovers over the largeImage
			largeImageText = "v{{custom.version}} ({{game.mods}} mods)"
			#The Asset ID or URLs of images to randomly use for the small image
			smallImageKey = ["{{images.player}}"]
			#The text to show when someone hovers over the smallImage
			smallImageText = "{{player.name}}"
			#The Twitch or Youtube URL to use when type is set to STREAMING
			streamingActivityUrl = "https://twitch.tv/twitch"

			#List of buttons (max 2) to show on the RPC
			[[dimension_overrides.dimensions.presence.buttons]]
				label = "comMC Project"
				url = "https://github.com/argo20k/comMC?tab=readme-ov-file#readme-top"

	[[dimension_overrides.dimensions]]
		#The name of the Dimension/Biome to override. FORMAT: modid:dimension or modid:biome
		name = "the_nether"

		#List of RPCs that will be displayed at random
		[[dimension_overrides.dimensions.presence]]
			#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
			type = "PLAYING"
			#The first line of text under the app name
			description = "{{player.name}} is in The Nether"
			#The second line of text under the app name
			state = ""
			#The Asset ID or URLs of images to randomly use for the large image
			largeImageKey = ["nether"]
			#The text to show when someone hovers over the largeImage
			largeImageText = "v{{custom.version}} ({{game.mods}} mods)"
			#The Asset ID or URLs of images to randomly use for the small image
			smallImageKey = ["{{images.player}}"]
			#The text to show when someone hovers over the smallImage
			smallImageText = "{{player.name}}"
			#The Twitch or Youtube URL to use when type is set to STREAMING
			streamingActivityUrl = "https://twitch.tv/twitch"

			#List of buttons (max 2) to show on the RPC
			[[dimension_overrides.dimensions.presence.buttons]]
				label = "comMC Project"
				url = "https://github.com/argo20k/comMC?tab=readme-ov-file#readme-top"

	[[dimension_overrides.dimensions]]
		#The name of the Dimension/Biome to override. FORMAT: modid:dimension or modid:biome
		name = "the_end"

		#List of RPCs that will be displayed at random
		[[dimension_overrides.dimensions.presence]]
			#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
			type = "PLAYING"
			#The first line of text under the app name
			description = "{{player.name}} is in The End"
			#The second line of text under the app name
			state = ""
			#The Asset ID or URLs of images to randomly use for the large image
			largeImageKey = ["end"]
			#The text to show when someone hovers over the largeImage
			largeImageText = "v{{custom.version}} ({{game.mods}} mods)"
			#The Asset ID or URLs of images to randomly use for the small image
			smallImageKey = ["{{images.player}}"]
			#The text to show when someone hovers over the smallImage
			smallImageText = "{{player.name}}"
			#The Twitch or Youtube URL to use when type is set to STREAMING
			streamingActivityUrl = "https://twitch.tv/twitch"

			#List of buttons (max 2) to show on the RPC
			[[dimension_overrides.dimensions.presence.buttons]]
				label = "comMC Project"
				url = "https://github.com/argo20k/comMC?tab=readme-ov-file#readme-top"

