#Show how many more lines there are that currently don't fit the tooltip, just like the vanilla shulker box tooltip.
#Default Value: true
last_line = true
#Show black chat background behind tooltip lines for better visibility.
#Default Value: RECTANGLE
#Allowed Values: NONE, RECTANGLE, ADAPTIVE
background = "RECTANGLE"
#Amount of ticks the held item tooltip will be displayed for. Set to 0 to always display the tooltip as long as an item is being held.
#Default Value: 40
# Default: 40
# Range: > 0
display_time = 60
#Offset on x-axis from screen center.
#Default Value: 0
# Default: 0
# Range: > -2147483648
offset_x = 0
#Allow other mods to modify held item tooltip contents. Lines could be both added or changed.
#Default Value: false
additional_tooltip_lines = false
#Offset on y-axis from screen center.
#Default Value: 59
# Default: 59
# Range: > 0
offset_y = 59
#Interval in ticks after which the tooltip will be rebuilt. Some stats such as durability are rebuilt every tick regardless of this setting.
#Default Value: 20
# Default: 20
# Range: > 1
update_interval = 20
#Disables held item tooltips for specified items, mainly to prevent custom tooltips from overlapping.
#Format for every entry is "<namespace>:<path>". Tags are supported, must be in the format of "#<namespace>:<path>". Namespace may be omitted to use "minecraft" by default. May use asterisk as wildcard parameter via pattern matching, e.g. "minecraft:*_shulker_box" to match all shulker boxes no matter of color. Begin an entry with "!" to make sure it is excluded, useful e.g. when it has already been matched by another pattern.
#Default Value: []
item_blacklist = []
#Scale of held item tooltips. Works together with "GUI Scale" option in "Video Settings". A smaller scale might make room for more rows.
#Default Value: 6
# Default: 6
# Range: 1 ~ 24
display_scale = 6
#Maximum amount of rows to be displayed for held item tooltips.
#Default Value: 4
# Default: 4
# Range: 1 ~ 12
max_lines = 5
#Should the tooltip or individual components on the tooltip be hidden when the "minecraft:tooltip_display" component is configured.
#Default Value: true
respect_tooltip_display_component = true

#Options for individual tooltip display entries.
[tooltip_lines]

	#Attributes this item provides when used or equipped, like attack damage and armor protection.
	[tooltip_lines.attribute_modifiers]
		#Should this tooltip component be included when rendering held item tooltips.
		#Default Value: false
		include = false
		#Priority for rendering this tooltip. When not enough lines are available (like an item with enchantments), components with a low priority will be skipped.
		#Default Value: 50
		# Default: 50
		# Range: > -2147483648
		priority = 50
		#Represent information for this component as if advanced tooltips were enabled independently of the actual setting.
		#Default Value: false
		advanced_tooltips = false
		#The order in which this tooltip component appears in relation to other components. Smaller values appear first.
		#Default Value: 50
		# Default: 50
		# Range: > -2147483648
		ordering = 50

		#Text formatting settings for this component's text appearance.
		[tooltip_lines.attribute_modifiers.formatting]
			#Should the text in this component appear bold.
			#Default Value: false
			bold = false
			#Should the text in this component appear struck-through.
			#Default Value: false
			strikethrough = false
			#The color of this component's text.
			#Default Value: default
			#Allowed Values: DEFAULT, BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE
			text_color = "default"
			#Should the text in this component be replaced by random characters.
			#Default Value: false
			obfuscated = false
			#Should the text in this component appear with an underline.
			#Default Value: false
			underline = false
			#Should the text in this component appear italic.
			#Default Value: false
			italic = false

	#A warning shown for an unavailable experimental item.
	[tooltip_lines.disabled]
		#Should this tooltip component be included when rendering held item tooltips.
		#Default Value: true
		include = true
		#Priority for rendering this tooltip. When not enough lines are available (like an item with enchantments), components with a low priority will be skipped.
		#Default Value: 10
		# Default: 10
		# Range: > -2147483648
		priority = 10
		#Represent information for this component as if advanced tooltips were enabled independently of the actual setting.
		#Default Value: false
		advanced_tooltips = false
		#The order in which this tooltip component appears in relation to other components. Smaller values appear first.
		#Default Value: 100
		# Default: 100
		# Range: > -2147483648
		ordering = 100

		#Text formatting settings for this component's text appearance.
		[tooltip_lines.disabled.formatting]
			#Should the text in this component appear bold.
			#Default Value: false
			bold = false
			#Should the text in this component appear struck-through.
			#Default Value: false
			strikethrough = false
			#The color of this component's text.
			#Default Value: default
			#Allowed Values: DEFAULT, BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE
			text_color = "default"
			#Should the text in this component be replaced by random characters.
			#Default Value: false
			obfuscated = false
			#Should the text in this component appear with an underline.
			#Default Value: false
			underline = false
			#Should the text in this component appear italic.
			#Default Value: false
			italic = false

	#Additional information supplied by individual items such as painting and smithing template information.
	[tooltip_lines.additional]
		#Should this tooltip component be included when rendering held item tooltips.
		#Default Value: true
		include = true
		#Priority for rendering this tooltip. When not enough lines are available (like an item with enchantments), components with a low priority will be skipped.
		#Default Value: 80
		# Default: 80
		# Range: > -2147483648
		priority = 80
		#Represent information for this component as if advanced tooltips were enabled independently of the actual setting.
		#Default Value: true
		advanced_tooltips = true
		#The order in which this tooltip component appears in relation to other components. Smaller values appear first.
		#Default Value: 20
		# Default: 20
		# Range: > -2147483648
		ordering = 20

		#Text formatting settings for this component's text appearance.
		[tooltip_lines.additional.formatting]
			#Should the text in this component appear bold.
			#Default Value: false
			bold = false
			#Should the text in this component appear struck-through.
			#Default Value: false
			strikethrough = false
			#The color of this component's text.
			#Default Value: default
			#Allowed Values: DEFAULT, BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE
			text_color = "default"
			#Should the text in this component be replaced by random characters.
			#Default Value: false
			obfuscated = false
			#Should the text in this component appear with an underline.
			#Default Value: false
			underline = false
			#Should the text in this component appear italic.
			#Default Value: false
			italic = false

	#Durability of this item, only shown if the item is damageable and has been used.
	[tooltip_lines.durability]
		#Should this tooltip component be included when rendering held item tooltips.
		#Default Value: true
		include = true
		#Priority for rendering this tooltip. When not enough lines are available (like an item with enchantments), components with a low priority will be skipped.
		#Default Value: 90
		# Default: 90
		# Range: > -2147483648
		priority = 90
		#Represent information for this component as if advanced tooltips were enabled independently of the actual setting.
		#Default Value: false
		advanced_tooltips = false
		#The order in which this tooltip component appears in relation to other components. Smaller values appear first.
		#Default Value: 70
		# Default: 70
		# Range: > -2147483648
		ordering = 70

		#Text formatting settings for this component's text appearance.
		[tooltip_lines.durability.formatting]
			#Should the text in this component appear bold.
			#Default Value: false
			bold = false
			#Should the text in this component appear struck-through.
			#Default Value: false
			strikethrough = false
			#The color of this component's text.
			#Default Value: default
			#Allowed Values: DEFAULT, BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE
			text_color = "default"
			#Should the text in this component be replaced by random characters.
			#Default Value: false
			obfuscated = false
			#Should the text in this component appear with an underline.
			#Default Value: false
			underline = false
			#Should the text in this component appear italic.
			#Default Value: false
			italic = false

	#Internal identifier of this item.
	[tooltip_lines.identifier]
		#Should this tooltip component be included when rendering held item tooltips.
		#Default Value: false
		include = false
		#Priority for rendering this tooltip. When not enough lines are available (like an item with enchantments), components with a low priority will be skipped.
		#Default Value: 30
		# Default: 30
		# Range: > -2147483648
		priority = 30
		#Represent information for this component as if advanced tooltips were enabled independently of the actual setting.
		#Default Value: false
		advanced_tooltips = false
		#The order in which this tooltip component appears in relation to other components. Smaller values appear first.
		#Default Value: 80
		# Default: 80
		# Range: > -2147483648
		ordering = 80

		#Text formatting settings for this component's text appearance.
		[tooltip_lines.identifier.formatting]
			#Should the text in this component appear bold.
			#Default Value: false
			bold = false
			#Should the text in this component appear struck-through.
			#Default Value: false
			strikethrough = false
			#The color of this component's text.
			#Default Value: default
			#Allowed Values: DEFAULT, BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE
			text_color = "default"
			#Should the text in this component be replaced by random characters.
			#Default Value: false
			obfuscated = false
			#Should the text in this component appear with an underline.
			#Default Value: false
			underline = false
			#Should the text in this component appear italic.
			#Default Value: false
			italic = false

	#Display name of the held item.
	[tooltip_lines.item_name]
		#Should this tooltip component be included when rendering held item tooltips.
		#Default Value: true
		include = true
		#Priority for rendering this tooltip. When not enough lines are available (like an item with enchantments), components with a low priority will be skipped.
		#Default Value: 100
		# Default: 100
		# Range: > -2147483648
		priority = 100
		#Represent information for this component as if advanced tooltips were enabled independently of the actual setting.
		#Default Value: false
		advanced_tooltips = false
		#The order in which this tooltip component appears in relation to other components. Smaller values appear first.
		#Default Value: 10
		# Default: 10
		# Range: > -2147483648
		ordering = 10

		#Text formatting settings for this component's text appearance.
		[tooltip_lines.item_name.formatting]
			#Should the text in this component appear bold.
			#Default Value: false
			bold = false
			#Should the text in this component appear struck-through.
			#Default Value: false
			strikethrough = false
			#The color of this component's text.
			#Default Value: default
			#Allowed Values: DEFAULT, BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE
			text_color = "default"
			#Should the text in this component be replaced by random characters.
			#Default Value: false
			obfuscated = false
			#Should the text in this component appear with an underline.
			#Default Value: false
			underline = false
			#Should the text in this component appear italic.
			#Default Value: false
			italic = false

	#The id of a map.
	[tooltip_lines.components]
		#Should this tooltip component be included when rendering held item tooltips.
		#Default Value: true
		include = true
		#Priority for rendering this tooltip. When not enough lines are available (like an item with enchantments), components with a low priority will be skipped.
		#Default Value: 70
		# Default: 70
		# Range: > -2147483648
		priority = 70
		#Represent information for this component as if advanced tooltips were enabled independently of the actual setting.
		#Default Value: false
		advanced_tooltips = false
		#The order in which this tooltip component appears in relation to other components. Smaller values appear first.
		#Default Value: 30
		# Default: 30
		# Range: > -2147483648
		ordering = 30

		#Text formatting settings for this component's text appearance.
		[tooltip_lines.components.formatting]
			#Should the text in this component appear bold.
			#Default Value: false
			bold = false
			#Should the text in this component appear struck-through.
			#Default Value: false
			strikethrough = false
			#The color of this component's text.
			#Default Value: default
			#Allowed Values: DEFAULT, BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE
			text_color = "default"
			#Should the text in this component be replaced by random characters.
			#Default Value: false
			obfuscated = false
			#Should the text in this component appear with an underline.
			#Default Value: false
			underline = false
			#Should the text in this component appear italic.
			#Default Value: false
			italic = false

	#Amount of components on this item.
	[tooltip_lines.component_count]
		#Should this tooltip component be included when rendering held item tooltips.
		#Default Value: false
		include = false
		#Priority for rendering this tooltip. When not enough lines are available (like an item with enchantments), components with a low priority will be skipped.
		#Default Value: 20
		# Default: 20
		# Range: > -2147483648
		priority = 20
		#Represent information for this component as if advanced tooltips were enabled independently of the actual setting.
		#Default Value: false
		advanced_tooltips = false
		#The order in which this tooltip component appears in relation to other components. Smaller values appear first.
		#Default Value: 90
		# Default: 90
		# Range: > -2147483648
		ordering = 90

		#Text formatting settings for this component's text appearance.
		[tooltip_lines.component_count.formatting]
			#Should the text in this component appear bold.
			#Default Value: false
			bold = false
			#Should the text in this component appear struck-through.
			#Default Value: false
			strikethrough = false
			#The color of this component's text.
			#Default Value: default
			#Allowed Values: DEFAULT, BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE
			text_color = "default"
			#Should the text in this component be replaced by random characters.
			#Default Value: false
			obfuscated = false
			#Should the text in this component appear with an underline.
			#Default Value: false
			underline = false
			#Should the text in this component appear italic.
			#Default Value: false
			italic = false
