#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Jun 23 00:37:27 AEST 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.5.1.zip
